CREATE DATABASE School;

USE School;

CREATE TABLE STUDENT (
Roll_no INT PRIMARY KEY,
Name VARCHAR(250),
Marks INT,
Grade VARCHAR(250)
);

INSERT INTO STUDENT (Roll_no,Name,Marks,Grade)
VALUES
(001, 'Shahana',85,'A'),
(002, 'Sihan',90,'A+'),
(003, 'soofiya',78,'B'),
(004, 'Aneesa',92,'A+'),
(005, 'Vishnu',88,'A');

SELECT * FROM STUDENT;

ALTER TABLE STUDENT ADD COLUMN Contact VARCHAR(255);

ALTER TABLE STUDENT DROP COLUMN Grade;

RENAME TABLE STUDENT TO CLASSTEN;

TRUNCATE TABLE CLASSTEN;

DROP TABLE CLASSTEN;
